### ISSUE TITLE
Cocoapods support

### ISSUE THREAD

**Issue by danshevluk** [vapor/sockets#112]
Hello there! You library is awesome but it's hard to use it in big iOS project without dependency manager support. Do you have plans to add Cocoapods support?

**Comment by banxi1988** [comment]
@danshevluk  Hi, I have the same problem.
while I just clone it to my project, and create two framework manually. (when add files to framework ,make sure to check the *Create folder references*).
then I can update the two framework just update the cloned repo

**Comment by LoganWright** [comment]
@danshevluk we've begun integrating some experimental cocoapods support into our model level libraries, We could probably add it here, but as we move up the chain to engine/vapor, we get some lower level difficulties w/ our LibreSSL C Dependencies

**Comment by danshevluk** [comment]
@banxi1988 I did the same thing, but it makes complicated to update library version. Maybe adding project with two frameworks to repo will make this a bit easier. Then, to use library you will have to add repos, add git submodule and add Socks subproject to your application.

**Comment by banxi1988** [comment]
@danshevluk  now I published a  VaporSockets(module_name='sockets') in cocoapods
In fact, In order to publish this pod, I have to create servel podspec file.
see: https://github.com/vapor/sockets/pull/122

**Comment by BrettRToomey** [comment]
Closing this in favour of #122
