### ISSUE TITLE
Access control on setOption and resolve

### ISSUE THREAD

**Issue by kydos** [vapor/sockets#125]
Hello,

I wonder why the operations listed below have internal access control:

-  InternetAddress.resolve
- Descriptor.(setOption | getOption | setBoolOption | getBoolOption)

The get/set Option operations are handy to change manipulate the socket options, for instance to join/leave a multicast group as well as to deal with the ADDR/PORT reuse.    

Likewise the resolve operation on the InternetAddress is kind of essential to send a datagram over an unconnected UDP socket. 

Ciao, Kydos

**Comment by tanner0101** [comment]
I'll look into publicizing those methods for 2.0.

**Comment by kydos** [comment]
Great thanks!

**Comment by tanner0101** [comment]
We've moved to a different setup now in Vapor 3. This should no longer be a problem.
