### ISSUE TITLE
Adding set/getReusePort to RawSocket

### ISSUE THREAD

**Issue by kydos** [vapor/sockets#126]
Hello,

    The semantics of SO_REUSEADDR and SO_REUSEPORT  is different and as a consequence both options are required when dealing with different cases. 

Below the code:

  ```
    public func setReusePort(_ newValue: Bool) throws {
        if isClosed { throw SocketsError(.socketIsClosed) }
        try descriptor.setBoolOption(level: SOL_SOCKET, name: SO_REUSEPORT, value: newValue)
    }
    
    public func getReusePort(_ newValue: Bool) throws -> Bool {
        if isClosed { throw SocketsError(.socketIsClosed) }
        return try descriptor.getBoolOption(level: SOL_SOCKET, name: SO_REUSEPORT)
    }
```

Ciao, Kydos

**Comment by tanner0101** [comment]
Are you asking for a method for setting `SO_REUSEADDR` to be added?

**Comment by kydos** [comment]
The method that sets the SO_REUSEADDR is already in place but that is not sufficient in some cases, e.g. UPD socket bound to 0.0.0.0:1234 that joins a multicast address say 239.255.0.1 and for which you may have multiple apps joining the same (multicast-addres,port) on the same host. On MacOS that requires you to set SO_REUSEPORT.

Makes sense?

**Comment by tanner0101** [comment]
We support reuse port now in Vapor 3.
