### ISSUE TITLE
How to enable UDP broadcast ?

### ISSUE THREAD

**Issue by congyuguo** [vapor/sockets#134]
When I send message to 192.18.1.255, I get this error: Error Socket failed with code 13 ("Permission denied") [sendFailedToSendAllBytes]. I believe it's because UDP broadcast is disabled by default, so how can I enable it ?

**Comment by tanner0101** [comment]
Hmm not quite sure. Possibly you could enable it using a C function and the socket descriptor?

```c
bcast_sock = socket(AF_INET, SOCK_DGRAM, 0);
int broadcastEnable=1;
int ret=setsockopt(bcast_sock, SOL_SOCKET, SO_BROADCAST, &broadcastEnable, sizeof(broadcastEnable));
```
