### ISSUE TITLE
Can I use this without Vapor? (and if so, how?)

### ISSUE THREAD

**Issue by jasonmemez** [vapor/sockets#145]
I am just looking for an easy, light socket framework when I stumbled across this. When i headed to the docs, i didn't expect to see all Vapor stuff. Searched up "socket", no good results. The readme has nothing in it. I am kind of confused. Could I have some clarification here?

**Comment by tanner0101** [comment]
We haven't written any docs for pure sockets yet. However, these are used in almost every Vapor package so there's a ton of example code if you look for it. Also the `Tests` folder in this repo would be a great place to start.

**Comment by mludi** [comment]
This issue should be closed.
